suspects_dna = {"ACAAGATGCCATTGTCCCCCGGCCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCCCTGCCCCTGGAGGGTGGCCCCACCGGCCGAGACAGCGAGCATATGCAGGAAGCGGCAGGAATAAGGAAAAGCAGCCTCCTGACTTTCCTCGCTTGGTGGTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGGAAGCTCGGGAGGTGGCCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGCGCGCCGGGACAGAATGCCCTGCAGGAACTTCTTCTGGAAGACCTTCTCCTCCTGCAAATAAAACCTCACCCATGAATGCTCACGCAAGTTTAATTACAGACCTGAA"}

#Hair color:

Black = "CCAGCAATCGC"
Brown = "GCCAGTGCCG"
Blonde = "TTAGCTATCGC"

#Facial shape:

Square = "GCCACGG"
Round = "ACCACAA"
Oval = "AGGCCTCA"

#Eye color:

Blue = "TTGTGGTGGC"
Green = "GGGAGGTGGC"
Brown = "AAGTAGTGAC"

#Gender:

Female = "TGAAGGACCTTC"
Male = "TGCAGGAACTTC"

#Race:

White = "AAAACCTCA"
Black = "CGACTACAG"
Asian = "CGCGGGCCG"